language: r
r: bioc-release
cache: packages

before_install:
  - tlmgr --repository ctan update --self
  - tlmgr --repository ctan update --all || true 
  - tlmgr --repository ctan install bera pdftexcmds nowidow parnotes marginfix infwarerr ragged2e

r_check_args:  --no-vignettes --timings

after_success:
  - travis_wait 20 Rscript codecov.R
